create or replace TABLE CUST_TBL (
	CUST_NUM VARCHAR(8),
	CUST_STAT VARCHAR(255),
	CUST_BAL NUMBER(20,0) MASKING POLICY DEMO_DB.PUBLIC.CUST_MASK_PII_NUM,
	INV_NO VARCHAR(10),
	INV_AMT NUMBER(10,0) MASKING POLICY DEMO_DB.PUBLIC.CUST_MASK_PII_NUM,
	CRID VARCHAR(4) MASKING POLICY DEMO_DB.PUBLIC.CUST_MASK_PII,
	SSN VARCHAR(10) MASKING POLICY DEMO_DB.PUBLIC.CUST_MASK_PII,
	PHONE NUMBER(10,0),
	EMAIL VARCHAR(50)
);
